import { createSlice } from "@reduxjs/toolkit";
import { Properties } from "../../types";

const initialState: Properties[] = [
  {
    name: "Villa Aroma",
    id: 1,
    details: "10/9/2024(Thur)\n17/9/2024",
    nights: 7,
    visitor: "Charis Mavr",
    total_amount: 1000,
    status: "Confirmed",
    city: "Rethymno",
  },
  {
    name: "Euphoria Villa",
    id: 2,
    details: "10/9/2024(Thur)\n20/9/2024",
    nights: 8,
    visitor: "Giannis Zoub",
    total_amount: 2000,
    status: "Pre Check-in",
    city: "Herakleion",
  },
  {
    name: "Harmony Retreat",
    id: 3,
    details: "11/9/2024(Fri)\n18/9/2024",
    nights: 7,
    visitor: "Sophia Nikos",
    total_amount: 1500,
    status: "Confirmed",
    city: "Chania",
  },
  {
    name: "Tranquil Villa",
    id: 4,
    details: "12/9/2024(Sat)\n19/9/2024",
    nights: 7,
    visitor: "Alexis Kontos",
    total_amount: 1800,
    status: "Pre Check-in",
    city: "Lasithi",
  },
  {
    name: "Serenity Estate",
    id: 5,
    details: "13/9/2024(Sun)\n20/9/2024",
    nights: 7,
    visitor: "Nikoleta Pavlou",
    total_amount: 2200,
    status: "Confirmed",
    city: "Rethymno",
  },
  {
    name: "Ocean Breeze Villa",
    id: 6,
    details: "14/9/2024(Mon)\n21/9/2024",
    nights: 7,
    visitor: "Dimitrios Kotsis",
    total_amount: 1900,
    status: "Pre Check-in",
    city: "Chania",
  },
  {
    name: "Mountain Peak Lodge",
    id: 7,
    details: "15/9/2024(Tue)\n22/9/2024",
    nights: 7,
    visitor: "Maria Konstantinou",
    total_amount: 1700,
    status: "Confirmed",
    city: "Herakleion",
  },
  {
    name: "Sunset Hills Villa",
    id: 8,
    details: "16/9/2024(Wed)\n23/9/2024",
    nights: 7,
    visitor: "Kostas Zervos",
    total_amount: 2100,
    status: "Pre Check-in",
    city: "Athens",
  },
  {
    name: "Emerald Villa",
    id: 9,
    details: "17/9/2024(Thur)\n24/9/2024",
    nights: 7,
    visitor: "Eleni Petrakis",
    total_amount: 2000,
    status: "Confirmed",
    city: "Thessaloniki",
  },
  {
    name: "Crystal Cove Villa",
    id: 10,
    details: "18/9/2024(Fri)\n25/9/2024",
    nights: 7,
    visitor: "Georgios Manos",
    total_amount: 2500,
    status: "Pre Check-in",
    city: "Paros",
  },
];

const propertiesSlice = createSlice({
  name: "properties",
  initialState,
  reducers: {},
});

export const propertiesActions = propertiesSlice.actions;
export default propertiesSlice.reducer;
