import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "@/src/app/[locale]/globals.css";

import { getMessages } from "next-intl/server";
import { StoreProvider } from "./[locale]/StoreProvider";
import PrimaryNavigation from "./[locale]/components/navigation/mainNavigation/primaryNavigation";
import SecondaryMainNavigation from "./[locale]/components/navigation/mainNavigation/secondaryNavigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className="">
				<StoreProvider>
					<NextIntlClientProvider
						messages={messages}
					>
						<div className="shadow-lg sticky top-0 z-10">
							<PrimaryNavigation />
							<SecondaryMainNavigation />
						</div>
						{children}
					</NextIntlClientProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
