import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "/home/charmavr/project/guests/src/app/[locale]/globals.css";

import { getMessages } from "next-intl/server";
import { StoreProvider } from "./[locale]/StoreProvider";
import Navigation from "./[locale]/ui/navigation/page";
import MainNavigation from "./[locale]/components/navigations/mainNavigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className="">
				<StoreProvider>
					<NextIntlClientProvider
						messages={messages}
					>
						<MainNavigation />
						{children}
					</NextIntlClientProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
