import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import "/home/charmavr/project/guests/src/app/[locale]/globals.css";


import { StoreProvider } from "./StoreProvider";
import { getMessages } from "next-intl/server";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {

  const messages = await getMessages()


  return (
    <html lang={locale}>
      <body className="">
        <StoreProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
